# Generated by Django 5.2.7 on 2025-10-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('completed_pass', models.BooleanField()),
                ('potential_assist', models.BooleanField()),
                ('turnover', models.BooleanField()),
                ('ball_start_loc_x', models.FloatField()),
                ('ball_start_loc_y', models.FloatField()),
                ('ball_end_loc_x', models.FloatField()),
                ('ball_end_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=50)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='app.game')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='app.player')),
            ],
            options={
                'db_table': 'passes',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('shooting_foul_drawn', models.BooleanField()),
                ('shot_loc_x', models.FloatField()),
                ('shot_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=50)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.game')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.player')),
            ],
            options={
                'db_table': 'shots',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tov_loc_x', models.FloatField()),
                ('tov_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=50)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='app.game')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='app.player')),
            ],
            options={
                'db_table': 'turnovers',
            },
        ),
    ]
